### ISSUE TITLE
Climate service fails

### ISSUE THREAD

**Issue by 6zXo8aMn2TRXOs** [Hyundai-Kia-Connect/hyundai_kia_connect_api#165]
**Region and Brand of car**
EU Kia

**Version of the integration**
2.0.40

**Describe the bug**
When Carling the climate service it fails.

**Debug logs if an error occurred**
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:178
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 16:51:27 (2 occurrences)
Last logged: 16:51:53

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: _check_response_for_errors() missing 1 required positional argument: 'response'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 70, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 178, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 102, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 504, in start_climate
    _check_response_for_errors()
TypeError: _check_response_for_errors() missing 1 required positional argument: 'response'

```

**To Reproduce**
Call service:
```
service: kia_uvo.start_climate
data:
  device_id: *******
  duration: 10
  defrost: true
  heating: "1"
  climate: true
  temperature: 21

```

**Comment by cdnninja** [comment]
@zulufoxtrot  Could you take a look at this one?  I moved from the HA issues since this looks like a core API issue.
