### ISSUE TITLE
R3.3.10 makes that EU Hyundai no longer works compared to R3.3.8 because of "pushType": "APNS"

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#354]
* Hyundai / Kia Connect version: R3.3.10
* Python version: 3.9.13
* Operating System: Windows 10

### Description

V3.3.8 fixed the EU Hyundai for this issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/348
However, the changes to fix also EU Kia (V3.3.10) makes that it no longer works for EU Hyundai.

### What I Did

"pushType": "APNS" is the problem for EU Hyundai, if I change it back to "pushType": "GCM", then it works again.
Apparently the pushType should be set dependent on EU Kia (APNS) or EU Hyundai (GCM).

Something like:
````
      if BRANDS[brand] == BRAND_KIA:
            self.PUSHTYPE : str = "APNS"
            .....
        elif BRANDS[brand] == BRAND_HYUNDAI:
            self.PUSHTYPE : str = "GCM"

.....
       "pushType": self.PUSHTYPE,
````

Below the exception for EU Hyundai when pushType is APNS.

```
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3107
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-03 13:01:59.949000+00:00 120000 46 998 46.495045125
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - Get Device ID request: https://prd.eu-ccapi.hyundai.com:8080/api/v1/spa/notifications/register {'ccsp-service-id': '6d477c38-3ca4-4cf3-9557-2a1929a94654', 'ccsp-application-id': '014d2225-8495-4735-812d-2616334fd15d', 'Stamp': 'dGpcIp3dP0dLfkNRUItk/sCdmouaEMW4JAlLv76lGxrWLqMbn3rTaiKVMiTPgdM=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd.eu-ccapi.hyundai.com:8080', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': '4e4521ce7a988ee66de549dfa7e55260b419230c162dd1ba5299f854e3650859', 'pushType': 'APNS', 'uuid': 'ecc69a3a-ca82-4a0b-816a-47208aea1243'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): prd.eu-ccapi.hyundai.com:8080
DEBUG:urllib3.connectionpool:https://prd.eu-ccapi.hyundai.com:8080 "POST /api/v1/spa/notifications/register HTTP/1.1" 400 132
Traceback (most recent call last):
  File "C:\Users\Rick\git\monitor\debug.py", line 117, in <module>
    vm.check_and_refresh_token()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 199, in login
    device_id = self._get_device_id(stamp)
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 1107, in _get_device_id
    _check_response_for_errors(response)
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 111, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'
```

**Comment by zulufoxtrot** [comment]
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/releases/tag/v3.3.11 should fix it :)

**Comment by JacklBirgit** [comment]
Bei mir das gleiche. Seit ein paar Tagen.
