### ISSUE TITLE
Infinite loop because of bluelinky-stamps generation outdated?

### ISSUE THREAD

**Issue by ZuinigeRijder** [Hyundai-Kia-Connect/hyundai_kia_connect_api#370]
* Hyundai / Kia Connect version:  v3.3.13
* Python version: 3.9+
* Operating System: Windows + Raspberry Pi

### Description

Since today the hyundai_kia_connect_api gets in an infinite loop.
Infinite loop is on line 1086 of KiaUvoApiEU.py: 
        if (position * 100.0) / stamp_count > 90:
            _LOGGER.debug("_get_stamp: (position * 100.0) / stamp_count > 90")
            self.stamps = None
            return self._get_stamp()

Added the _Logger.debug statement there, so recursion till fails.
Am I the only one? Is the bluelinky-stamps generation no longer valid since today?
So there is now an infinite loop....

Looks like the timestamps are 2 days old (it is 2023-07-29 today):
get_stamp 2023-07-27 13:01:47.588000+00:00

### What I Did

Added debug commands, run hyundai_kia_connect_monitor test program debug.py:

```
monitor>python debug.py
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3112
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-27 13:01:47.588000+00:00 120000 1335 998 1335.6188112333334
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:_get_stamp: (position * 100.0) / stamp_count > 90
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3112
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-27 13:01:47.588000+00:00 120000 1335 998 1335.6206157083334
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:_get_stamp: (position * 100.0) / stamp_count > 90
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3112
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-27 13:01:47.588000+00:00 120000 1335 998 1335.6226047333332
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:_get_stamp: (position * 100.0) / stamp_count > 90
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3112
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-27 13:01:47.588000+00:00 120000 1335 998 1335.62409055
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:_get_stamp: (position * 100.0) / stamp_count > 90
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3112
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-27 13:01:47.588000+00:00 120000 1335 998 1335.6259479666667
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:_get_stamp: (position * 100.0) / stamp_count > 90
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /neoPix/bluelinky-stamps/master/hyundai-014d2225-8495-4735-812d-2616334fd15d.v2.json HTTP/1.1" 200 3112
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:hyundai_kia_connect_api - get_stamp 2023-07-27 13:01:47.588000+00:00 120000 1335 998 1335.6274858583333
DEBUG:hyundai_kia_connect_api.KiaUvoApiEU:_get_stamp: (position * 100.0) / stamp_count > 90
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
Traceback (most recent call last):
  File "C:\Users\Rick\git\monitor\debug.py", line 117, in <module>
    vm.check_and_refresh_token()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 206, in login
    stamp = self._get_stamp()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 1089, in _get_stamp
    return self._get_stamp()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 1089, in _get_stamp
    return self._get_stamp()
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 1089, in _get_stamp
    return self._get_stamp()
  [Previous line repeated 3 more times]
  File "C:\Users\Rick\git\monitor\hyundai_kia_connect_api\KiaUvoApiEU.py", line 1073, in _get_stamp
    self.stamps = requests.get(self.stamps_url).json()
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by ZuinigeRijder** [comment]
Besides the timestamp generation is outdated, the question is if the infinite recursion _get_stamp, which ends eventually in an overflow is the good strategy. Should there only be a finite times of retry in the hyundai_kia_connect_api?

**Comment by ZuinigeRijder** [comment]
Issue of outdated timestamp generation here:
https://github.com/neoPix/bluelinky-stamps/issues/11

**Comment by ZuinigeRijder** [comment]
@cdnninja Thanks for the merge.
