### ISSUE TITLE
AttributeError: 'Token' object has no attribute 'vehicle_id' when calling check_and_refresh_token()

### ISSUE THREAD

**Issue by jacobian** [Hyundai-Kia-Connect/hyundai_kia_connect_api#43]
* Hyundai / Kia Connect version: 1.26.5
* Python version: 3.9
* Operating System: macOS 12.1

### Description

I'm getting an attribute error - `'Token' object has no attribute 'vehicle_id'` -- when calling `VehicleManager.check_and_refresh_token()`. 

Looking at the source, I think it's because `vehicle_id` is an attibute on `Vehicle`, not on Token; I think this is a bug [in HyundaiBlueLinkAPIUSA.py, line 293](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py#L293) -- I believe that should read `headers["vehicleId"] = vehicle.id`?

I'll try to open a PR, but I wanted to open the issue in case my theory is wrong.

### What I Did

```
>>> import hyundai_kia_connect_api as hkapi
>>> vm = hkapi.VehicleManager(
...     region=3,
...     brand=2,
...     username="xxx@xxx.xxx",
...     password="xxx",
...     pin="xxx",
... )
>>> vm.check_and_refresh_token()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 86, in check_and_refresh_token
    self.initialize()
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 51, in initialize
    self.update_all_vehicles_with_cached_state()
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 158, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 154, in _get_cached_vehicle_state
    vehicle_status["vehicleLocation"] = self.get_location(token, vehicle)
  File "/Users/jacob/Library/Caches/pypoetry/virtualenvs/ioniq-U4yWA9lt-py3.9/lib/python3.9/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 293, in get_location
    headers["vehicleId"] = token.vehicle_id
AttributeError: 'Token' object has no attribute 'vehicle_id'
>>>
```

**Comment by cdnninja** [comment]
You are correct! USA regions haven't had much testing so any support is appreciated.  Feel free to drop a PR.

**Comment by cdnninja** [comment]
As a note please check if this is still current in the latest release.   Some issues were resolved in that brand recently.
