### ISSUE TITLE
Missing entities : EV Battery level

### ISSUE THREAD

**Issue by yoan31** [Hyundai-Kia-Connect/hyundai_kia_connect_api#477]
* Hyundai Connect version: 1.33.0
* Python version: 3.11
* Operating System: hassio
* Hyundai Kona 2024 Full Electric

### Description

I'm missing the entities EV Battery Level.

I get the following errror in the log:

```
Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: /usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py:339
First occurred: 22:51:06 (1 occurrences)
Last logged: 22:51:06

Failed to parse driving info. Possible reasons: - incompatible vehicle (ICE) - new API format - API outage
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 334, in update_vehicle_with_cached_state
    state = self._get_driving_info(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1073, in _get_driving_info
    and drivingInfoItem["calculativeOdo"] > 0
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'calculativeOdo'

```

**Comment by jwillemsen** [comment]
I think #480 will fix this, similar to #440

**Comment by cdnninja** [comment]
Try test the latest.

**Comment by oystersoft** [comment]
Device info CD PHEV 20 by Kia Europe
HA 2024.3.1
Kia Uvo / Hyundai Bluelink ( latest version via HACS )

---------------------------------------------------------

Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: /usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py:362
First occurred: March 17, 2024 at 07:15:22 (9 occurrences)
Last logged: 05:16:50

Failed to parse driving info. Possible reasons: - incompatible vehicle (ICE) - new API format - API outage
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 357, in update_vehicle_with_cached_state
    state = self._get_driving_info(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1382, in _get_driving_info
    and drivingInfoItem["calculativeOdo"] > 0
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'calculativeOdo'

---------------------------------------------------------

Logger: hyundai_kia_connect_api.KiaUvoApiEU
Source: /usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py:389
First occurred: March 17, 2024 at 09:15:49 (3 occurrences)
Last logged: March 17, 2024 at 17:16:47

Failed to parse driving info. Possible reasons: - new API format - API outage
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 384, in force_refresh_vehicle_state
    state = self._get_driving_info(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1382, in _get_driving_info
    and drivingInfoItem["calculativeOdo"] > 0
        ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'calculativeOdo'
