### ISSUE TITLE
hyundai_kia_connect_api.VehicleManager import fails

### ISSUE THREAD

**Issue by ot3** [Hyundai-Kia-Connect/hyundai_kia_connect_api#52]
* Hyundai / Kia Connect version: hyundai-kia-connect-api-1.31.0
* Python version: 3.8.10
* Operating System: Ubuntu Server 20.04 running on a ProxMox 7 LXC container

### Description

I'm trying to run a very simple program to test whether I can login via the API but it already fails at the import statement.

### What I Did

Code:
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os

from hyundai_kia_connect_api.VehicleManager import *
```
Output:

```
pi@ha[~/kia] ~/kia/login-test.py
Traceback (most recent call last):
  File "/home/pi/kia/login-test.py", line 6, in <module>
    from hyundai_kia_connect_api.VehicleManager import *
  File "/usr/local/lib/python3.8/dist-packages/hyundai_kia_connect_api/__init__.py", line 3, in <module>
    from .ApiImpl import ApiImpl, ClimateRequestOptions
  File "/usr/local/lib/python3.8/dist-packages/hyundai_kia_connect_api/ApiImpl.py", line 28, in <module>
    class ApiImpl:
  File "/usr/local/lib/python3.8/dist-packages/hyundai_kia_connect_api/ApiImpl.py", line 39, in ApiImpl
    def get_vehicles(self, token: Token) -> list[Vehicle]:
TypeError: 'type' object is not subscriptable
```

I left out the rest of the code since it didn't even make it past the import statement.

**Comment by cdnninja** [comment]
You try 
from hyundai_kia_connect_api import *

**Comment by ot3** [comment]
I tried your suggestion: no difference; same error.

```
pi@ha[~] ~/kia/login-test.py
Traceback (most recent call last):
  File "/home/pi/kia/login-test.py", line 6, in <module>
    from hyundai_kia_connect_api import *
  File "/usr/local/lib/python3.8/dist-packages/hyundai_kia_connect_api/__init__.py", line 3, in <module>
    from .ApiImpl import ApiImpl, ClimateRequestOptions
  File "/usr/local/lib/python3.8/dist-packages/hyundai_kia_connect_api/ApiImpl.py", line 28, in <module>
    class ApiImpl:
  File "/usr/local/lib/python3.8/dist-packages/hyundai_kia_connect_api/ApiImpl.py", line 39, in ApiImpl
    def get_vehicles(self, token: Token) -> list[Vehicle]:
TypeError: 'type' object is not subscriptable

```

**Comment by ot3** [comment]
I've also tried this test on a different, in this case bare metal, Ubuntu system (Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-143-generic x86_64)) with a different result:

```
pi@eon:[~/ev]: ~/ev/login-test.py
Traceback (most recent call last):
  File "/home/pi/ev/login-test.py", line 6, in <module>
    from hyundai_kia_connect_api import *
  File "/usr/local/lib/python3.6/dist-packages/hyundai_kia_connect_api/__init__.py", line 3, in <module>
    from .ApiImpl import ApiImpl, ClimateRequestOptions
  File "/usr/local/lib/python3.6/dist-packages/hyundai_kia_connect_api/ApiImpl.py", line 3, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

```

**Comment by cdnninja** [comment]
I just noticed you have an old version of python. I believe 3.9 is required.   

I can update the docs.

**Comment by ot3** [comment]
You're right; it works now. I had to create a separate environment and upgrade to Python 3.9.5. For anyone else having this problem, here are the commands I used:

```
mkdir tmp
cd tmp
sudo wget -c https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
sudo chmod +x Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh
conda create -n kia python=3.9.5
sudo pip3 install hyundai_kia_connect_api
pip3 install pytz
pip3 install python-dateutil

NOTE: first line of Python code:

#!/home/pi/miniconda3/envs/kia/bin/python3.9

```
