### ISSUE TITLE
Hyundai / Kia Connect version: 3.20.6 fails since 2024-06-05

### ISSUE THREAD

**Issue by ultima-originem** [Hyundai-Kia-Connect/hyundai_kia_connect_api#575]
-   Hyundai / Kia Connect version: 3.20.6
-   Python version: 3.9
-   Operating System: Ubuntu

### Description

My production code fails since 2024-06-05. For this, I'm using a small test program derived from [eu_login_test.py](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/master/tests/eu_login_test.py). The code is as follows:

```
#!/home/pi/miniconda3/envs/kia/bin/python3.9
# -*- coding: utf-8 -*-

import os
from hyundai_kia_connect_api.VehicleManager import VehicleManager

def test_EU_login():
    username = 'xxx'
    password = 'yyy'
    pin = '000'

    vm = VehicleManager(region=1, brand=1, username=username, password=password, pin=pin)
    vm.check_and_refresh_token()
    vm.update_all_vehicles_with_cached_state()
    assert len(vm.vehicles.keys()) > 0
    print('VEHICLES: ', vm.vehicles)

test_EU_login()
```
This yields the following error:

```
(kia) pi@kia[~/kia/tests] ./login-test.py
Traceback (most recent call last):
  File "/home/pi/kia/tests/./login-test.py", line 18, in <module>
    test_EU_login()
  File "/home/pi/kia/tests/./login-test.py", line 13, in test_EU_login
    vm.check_and_refresh_token()
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 130, in check_and_refresh_token
    self.initialize()
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 74, in initialize
    self.token: Token = self.api.login(self.username, self.password)
  File "/home/pi/miniconda3/envs/kia/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 260, in login
    raise AuthenticationError("Login Failed")
hyundai_kia_connect_api.exceptions.AuthenticationError: Login Failed

```

Is this a known problem? Does the test program have to be updated?

**Comment by ultima-originem** [comment]
Never mind; password issue.
