### ISSUE TITLE
name 'location' is not defined

### ISSUE THREAD

**Issue by briansfriend** [Hyundai-Kia-Connect/hyundai_kia_connect_api#59]
* Hyundai / Kia Connect version: 1.34.1
* Python version: 3.9
* Operating System: Raspberry OS

### Description
The sample code on Hyundai EU returns "name 'location' is not defined"
I used a real account.

### What I Did

```
from hyundai_kia_connect_api import VehicleManager
vm = VehicleManager(region=1,
                    brand=2,
                    username="test@test.com",
                    password="testtest",
                    pin="")
vm.check_and_refresh_token()
vm.update_all_vehicles_with_cached_state()
print(vm.vehicles)
```

returns:
```
hyundai_kia_connect_api - Get vehicle location failed
Traceback (most recent call last):
  File "/home/pi/hyundai_api.py", line 7, in <module>
    vm.check_and_refresh_token()
  File "/home/pi/.local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 88, in check_and_refresh_token
    self.initialize()
  File "/home/pi/.local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 51, in initialize
    self.update_all_vehicles_with_cached_state()
  File "/home/pi/.local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 58, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
  File "/home/pi/.local/lib/python3.9/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 61, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/home/pi/.local/lib/python3.9/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 315, in update_vehicle_with_cached_state
    self.get_last_updated_at(get_child_value(location, "vehicleLocation.time")),
NameError: name 'location' is not defined
```

**Comment by Jazzman82** [comment]
I just stumbled over the same problem. Changed "location" to "state" in KiaUvoAPIEU.py, Line 315 and now it seems to work...

**Comment by cdnninja** [comment]
Should be good now.
