### ISSUE TITLE
Error in ApiImpl.py 

### ISSUE THREAD

**Issue by christoph623** [Hyundai-Kia-Connect/hyundai_kia_connect_api#60]
* Hyundai / Kia Connect version: 1.34.1
* Python version: 3.8.10
* Operating System: ubuntu xernial

### Description

simple by including from hyundai_kia_connect_api import * i get a python error

### What I Did

```
Traceback (most recent call last):
  File "1", line 1, in <module>
    from hyundai_kia_connect_api import *
  File "/u/src/hyundai_kia_connect_api-1.34.1/hyundai_kia_connect_api/__init__.py", line 3, in <module>
    from .ApiImpl import ApiImpl, ClimateRequestOptions
  File "/u/src/hyundai_kia_connect_api-1.34.1/hyundai_kia_connect_api/ApiImpl.py", line 27, in <module>
    class ApiImpl:
  File "/u/src/hyundai_kia_connect_api-1.34.1/hyundai_kia_connect_api/ApiImpl.py", line 38, in ApiImpl
    def get_vehicles(self, token: Token) -> list[Vehicle]:
TypeError: 'type' object is not subscriptable

**Comment by briansfriend** [comment]
You need to update to python 3.9 or higher. 
See https://docs.python.org/3.9/library/typing.html
